### ISSUE TITLE
Windows test in .travis

### ISSUE THREAD

**Issue by alegresor** [QMCSoftware/QMCSoftware#134]

**Comment by jagadeesr** [comment]
It looks like Travis CI, the test build server does not support windows.
They are still working on it.
Getting Error while trying to launch the test:
>>  Windows builds are in early access stage. Please head to the Travis CI Community forum to get help or post ideas.
>> Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com.

I think we should leave Windows out for now.

On Thu, Jan 30, 2020 at 5:51 PM alegresor <notifications@github.com> wrote:
>
> Assigned #134 to @jagadeesr.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
-Jags
