### ISSUE TITLE
Generic covariance Gaussian measure

### ISSUE THREAD

**Issue by mikemccourt** [QMCSoftware/QMCSoftware#138]
Is it possible to have a covariance for qp.Gaussian()?  I can transform the points manually, but what I really want to do is call `qp.Gaussian(dimension, mean=0, covariance=matrix)` for some arbitrary SPD `matrix`.  Is there a way to do this now?  I can work on a PR if not, I just didn't want to start on something if it was already being dealt with.

**Comment by sou-cheng-choi** [comment]
Great suggestion!
