### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by mikemccourt-sigopt** [QMCSoftware/QMCSoftware#143]
Hey guys.  I know I said push the version, but I'm wondering how much work it would be to support Python>=3.6.4?  Are we using anything in the `python_prototype` which actually requires 3.7?

**Comment by sou-cheng-choi** [comment]
Hi Mike, 

I don’t think it would be too much work. We could set up an additional virtual environment for 3.6.4, and make sure all unit tests passing there. Let us know if you think this is a good plan. 

Sou-Cheng
