### ISSUE TITLE
QMCPy for Windows

### ISSUE THREAD

**Issue by alegresor** [QMCSoftware/QMCSoftware#156]
- get `pip install qmcpy` working for Windows
- include Travis test for Windows

**Comment by nikolasharing** [comment]
Is there a workaround for windows in the meantime?

**Comment by alegresor** [comment]
Using a linux subsystem should allow the pip install to complete successfully.

**Comment by nikolasharing** [comment]
This is probably not possible for me, is there another way? Cloning the repository and istalling it by myself or something like that? Or is it possible for someone to build a wheel and post that? (I do not know if that would work, but building the wheel seems to be the problem currently, at least for me.)

**Comment by alegresor** [comment]
You can try out QMCPy on a Google Colab notebook while we work through the Windows errors. See [this](https://tinyurl.com/QMCPyTutorial) tutorial Fred Hickernell gave at MCQMC2020 as a reference (you will need to make a copy to be able to edit).

**Comment by nikolasharing** [comment]
Works like a charm if one only wants to generate points and download them as a file. Thank you very much!

**Comment by alegresor** [comment]
We have just made a new release of QMCPy on PyPi [here](https://pypi.org/project/qmcpy/0.7/). This version should be compatible with Windows. Let us know if you are still having trouble with the install.

**Comment by nikolasharing** [comment]
Works like a charm. Perfect. Thank you so much!

**Comment by fjhickernell** [comment]
Dear Nikolas,

Thanks for the feedback.  Please share your experience with us and if there is a feature that you would like to see or contribute.

Best,
Fred


Fred J. Hickernell
Vice Provost for Research, research.iit.edu <https://research.iit.edu/>
www.iit.edu/research/about/magazine <https://www.iit.edu/research/about/magazine>
Professor, Department of Applied Mathematics
Center for Interdisciplinary Scientific Computation (CISC) cos.iit.edu/cisc/ <https://cos.iit.edu/cisc/>
Illinois Institute of Technology
IIT Tower, Room 7C9-2, 10 W 35th St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, +1 312 567 3470 <tel:+1%20312%20567%203470>  

Working remotely.  Please contact me by email or phone.
