### ISSUE TITLE
Issue on fixing a seed globally

### ISSUE THREAD

**Issue by jungtaekkim** [QMCSoftware/QMCSoftware#222]
Hi,

Thank you for developing this useful project!

However, it fixes a seed globally and it affects my other codes.

For example, this part causes this problem:
https://github.com/QMCSoftware/QMCSoftware/blob/4518d26b06ef737797d5e522cb61d9f7b516d74e/qmcpy/discrete_distribution/sobol/sobol.py#L205

I think it can be easily fixed like

random.RandomState(seeds).randint()

Please fix it or please let me know where I can send a pull request (e.g., name of branch).

Thanks a lot.

**Comment by fjhickernell** [comment]
Dear Jungtaek,

Thank you so much for pointing out this problem.  We appreciate your feedback.  Aleksei will take a look and either offer a fix or ask you for further information.

Best,
Fred


Fred J. Hickernell
Vice Provost for Research, research.iit.edu <https://research.iit.edu/>
www.iit.edu/research/about/magazine <https://www.iit.edu/research/about/magazine>
Professor, Department of Applied Mathematics
Center for Interdisciplinary Scientific Computation (CISC) cos.iit.edu/cisc/ <https://cos.iit.edu/cisc/>
Illinois Institute of Technology
IIT Tower, Room 7C9-2, 10 W 35th St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, +1 312 567 3470 <tel:+1%20312%20567%203470>  

Working remotely.  Please contact me by email or phone.

**Comment by mikemccourt-intel** [comment]
Jungtaek, thank you for using QMCPy!  You make a very interesting point.  If you'd like to make a PR, please feel free to do so.  Maybe in a branch named `random-seed`?  Do you have a sense on how we would write a tests to confirm the desired behavior?  That might be helpful in that branch as well.

**Comment by mikemccourt** [comment]
Jungtaek, thank you for using QMCPy! You make a very interesting point. If you'd like to make a PR, please feel free to do so. Maybe in a branch named random-seed? Do you have a sense on how we would write a tests to confirm the desired behavior? That might be helpful in that branch as well.

**Comment by jungtaekkim** [comment]
Hi Mike and Fred,

I will send a pull request for the preliminary commit related this issue.

Please review it.

Best regards,
Jungtaek.

**Comment by fjhickernell** [comment]
Thanks for pointing this out!
I pushed a change to the develop branch, let me know if the issue persists.
