### ISSUE TITLE
Recovering code coverage reports by Github Actions tests

### ISSUE THREAD

**Issue by sou-cheng-choi** [QMCSoftware/QMCSoftware#235]

**Comment by alegresor** [comment]
all reports are available from https://app.codecov.io/gh/QMCSoftware/QMCSoftware

computed / uploaded with [this block](https://github.com/QMCSoftware/QMCSoftware/blob/master/.github/workflows/python-package-conda.yml#L29) and displayed in the README via [this line](https://github.com/QMCSoftware/QMCSoftware/blob/master/README.md?plain=1#L2).
