### ISSUE TITLE
Different answers of Asian Option

### ISSUE THREAD

**Issue by yding2** [QMCSoftware/QMCSoftware#253]
---
name: Bug report
about: Create a report to help us improve
title: 'Different answers of Asian Option'
labels: ''
assignees: ''

---

**System information**
 - OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  OS
 - Are you using google COLAB notebook: (Yes/No) No
 - Browser if using Jupyter [e.g. chrome, safari] Safari
 - Browser version if using Jupyter [e.g. 22]
 - Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
 - QMCPy installed from (source or binary):  source
 - QMCPy version: 
 - Python version: 3.7
 - Installed using virtualenv? pip? conda?: Pip
 - GCC or Windows C Compiler version: 

**Describe the problem**
I tried to price an Asian arithmetic mean call option with initial price = strike price = 120, volatility = 0. 5, interest rate = 0.02, maturity time = 1/4 and monitor every week. Abstol = 0.05. I got different answers when I used QMCPy and GAIL.

**To Reproduce**
Steps to reproduce the behavior: [Jupyter notebook](https://drive.google.com/file/d/14u-RPN4eMIBu9fmTLGi8lJLK5oKN68my/view?usp=sharing) GAIL with [the code](https://drive.google.com/file/d/1L3d8DXDAQSHwe5PQqV513fLFUyrHZzQy/view?usp=sharing)
There is another case. [Jupyter notebook](https://drive.google.com/file/d/1QL45RZLdeIoOeJnnc8prkK7JmrHNAw33/view?usp=sharing) ; [M-file](https://drive.google.com/file/d/1Zobrh5lpWxSdymQcNYEF4oh_wxgVFoyD/view?usp=sharing)

**Expected behavior**
Two results should be the same.

**Screenshots**
Results of QMCPy
![Screen Shot 2021-06-24 at 3.05.17 PM.png](https://images.zenhubusercontent.com/60d49e962427baf8362763e0/3474f87b-5cd3-48ba-8383-adde06c19c9e)
Results of MATLAb
![asian_option](https://user-images.githubusercontent.com/1869047/123729406-8c73fd00-d85a-11eb-80e8-72adb1c8008e.png)

**Comment by fjhickernell** [comment]
Interesting.  One thought is whether the discretizations are the same:  are both discretizing log(S)?  Are both using a right rectangle rule?

Best,
Fred


Fred J. Hickernell
Vice Provost for Research, research.iit.edu <https://research.iit.edu/>
www.iit.edu/research/about/magazine <https://www.iit.edu/research/about/magazine>
Professor, Department of Applied Mathematics
Center for Interdisciplinary Scientific Computation (CISC) cos.iit.edu/cisc/ <https://cos.iit.edu/cisc/>
Illinois Institute of Technology
IIT Tower, Room 7C9-2, 10 W 35th St, Chicago, IL 60616
***@***.*** ***@***.***>, +1 312 567 3470 <tel:+1%20312%20567%203470>  

Working remotely.  Please contact me by email or phone.
