### ISSUE TITLE
Sobol' Speed in QMCPy vs SciPy

### ISSUE THREAD

**Issue by alegresor** [QMCSoftware/QMCSoftware#254]
SciPy recently released a QMC module that includes a nice Sobol' generator. The script and output below show QMCPy's Sobol' becomes significantly slower than SciPy's as the dimension grows for a low number of samples. 

I suspect there may be some overhead for QMCPy to load in the Sobol' generator from C and the large generating vector. I've moved the default generating vector into the C library so it will not need to be loaded every time, but this did not seem to help much. 

Any ideas would be helpful! I'll reach out to the SciPy team and see if they can help too. 

```python 
import qmcpy
import scipy 
import numpy as np
import pandas as pd 
from time import time
from matplotlib import pyplot

dvec = 2**np.arange(9)
D = len(dvec)
mvec = np.arange(21)
M = len(mvec)
trials = 10
fig,ax = pyplot.subplots(nrows=D,ncols=1,figsize=(5,5*D))

for j in range(D):
    d = dvec[j]
    print('d = %d'%d)
    sobol_qmcpy = qmcpy.Sobol(d)
    sobol_scipy = scipy.stats.qmc.Sobol(d)
    times_qmcpy = np.zeros((trials,M),dtype=float)
    times_scipy = np.zeros((trials,M),dtype=float)
    print('\t%-10s%-15s%-15s'%('m','qmcpy','scipy'))
    for k in range(M):
        m = mvec[k]
        for t in range(trials):    
            # qmcpy
            t0 = time()
            samples = sobol_qmcpy.gen_samples(n_min=0,n_max=2**m)
            times_qmcpy[t,k] = time()-t0
            # scipy
            t0 = time()
            sobol_scipy.reset()
            samples = sobol_scipy.random_base2(m=m)
            times_scipy[t,k] = time()-t0
        average_this_m_qmcpy = times_qmcpy[:,k].mean()
        average_this_m_scipy = times_scipy[:,k].mean()
        print('\t%-10d%-15.1e%-15.1e'%(m,average_this_m_qmcpy,average_this_m_scipy))
    print()
    ax[j].plot(2**mvec,times_qmcpy.mean(0),color='c',label='qmcpy')
    ax[j].plot(2**mvec,times_scipy.mean(0),color='g',label='scipy')
    ax[j].set_xlabel('n')
    ax[j].set_ylabel('time')
    ax[j].set_xscale('log',basex=2)
    ax[j].set_yscale('log',basey=10)
    ax[j].set_xlim([2**mvec[0],2**mvec[-1]])
    ax[j].set_title('d = %d'%d)
ax[0].legend()
fig.tight_layout()
fig.savefig('_ags/temp.png',dpi=100)
```
![temp.png](https://images.zenhubusercontent.com/5db8d446b43a150001133d03/ee96334e-7483-41d6-ba8f-852e41147e7f)

**Comment by tupuinui** [comment]
Hi, SciPy maintainer here. I had a chat with Fred who told me about this.

Our code is in Cython and we release the GIL so it should benefit from threads. But we did not try to add more parallelism yet. Regarding the loading of the direction number, if you call once `scipy.stats.qmc.Sobol`, it will initialize the array for the rest of the Python session. So all following calls to `scipy.stats.qmc.Sobol` would be fast.

The loading is done in Cython from a compressed array, and the values have been pre-processed to save space and make it directly ready to be used.

**Comment by tupui** [comment]
Hi, SciPy maintainer here. I had a chat with Fred who told me about this.

Our code is in Cython and we release the GIL so it should benefit from threads. But we did not try to add more parallelism yet. Regarding the loading of the direction number, if you call once `scipy.stats.qmc.Sobol`, it will initialize the array for the rest of the Python session. So all following calls to `scipy.stats.qmc.Sobol` would be fast.

The loading is done in Cython from a compressed array, and the values have been pre-processed to save space and make it directly ready to be used.

**Comment by alegresor** [comment]
> Hi, SciPy maintainer here. I had a chat with Fred who told me about this.
> 
> Our code is in Cython and we release the GIL so it should benefit from threads. But we did not try to add more parallelism yet. Regarding the loading of the direction number, if you call once `scipy.stats.qmc.Sobol`, it will initialize the array for the rest of the Python session. So all following calls to `scipy.stats.qmc.Sobol` would be fast.
> 
> The loading is done in Cython from a compressed array, and the values have been pre-processed to save space and make it directly ready to be used.

Hi Pamphile, thanks for following up on this! I've been working on refactoring our digital net generator in https://github.com/QMCSoftware/QMCSoftware/tree/sobol_refactor. I'll keep this thread updated as we get some more progress. You're SciPy files have been very helpful, thanks again!

**Comment by tupui** [comment]
Great, glad this was helping you.

Also, saying this here. If there is anything that you feel would be missing or wrong in our new module, feel free to ping me or even open an issue/PR.

**Comment by alegresor** [comment]
![temp](https://user-images.githubusercontent.com/39531535/188971972-4873714b-51c7-42d9-867d-f4f848089e5a.png)

**Comment by tupui** [comment]
Nice timings @alegresor. Did you try this with the latest SciPy 1.9? Because I improved the performances there.

**Comment by alegresor** [comment]
Here are the most recent results based on SciPy 1.9.1
![temp](https://user-images.githubusercontent.com/39531535/189145287-47a035a9-c786-475a-a934-f8e22e59838e.png)

**Comment by tupui** [comment]
Interesting, do you have some explanation for the difference with low n? I thought it could be the init time, but the first point seems to indicate something else for your code, or there is a bug with this data point.

**Comment by alegresor** [comment]
Thanks for pointing this out! I'm not 100% sure what is going on. Perhaps there is some overhead in calling the C module for the first time. I'll look more into this.
