### ISSUE TITLE
Gpytorch dependency in QMCPy 1.4.4

### ISSUE THREAD

**Issue by mblaszkiewicz** [QMCSoftware/QMCSoftware#333]
Hi all, 

Just to let you know, it seems that the latest QMCPy available via PyPi (1.4.4) has a new dependency of gpytorch - and the most standard installation via PyPI makes QMCPy's import fail.

**System information**
 - QMCPy version: 1.4.4
 - Python version: 3.11
 - Installed using virtualenv? pip? conda?: virtualenv + pip

**Describe the problem**
When I do the most straight-forward installation of QMCPy, i.e., `pip install qmcpy` and try to import it, I get an error that gpytorch is not defined.

I briefly looked into the source files and it seems like your intent may have been to make the dependency optional with a try catch block, but its use in the code later on makes the import of QMCPy fail.

**Logs / Any other info**
```
File "[...]/env/lib/python3.11/site-packages/qmcpy/accumulate_data/pf_gp_ci_data.py", line 227, in <module>
    class ExactGPyTorchRegressionModel(gpytorch.models.ExactGP):
NameError: name 'gpytorch' is not defined
```

after running `import qmcpy`.

**Comment by sou-cheng-choi** [comment]
This file exists only in "develop" branch. So instead of doing "pip install qmcpy", you need to set up a development environment for QMCPy following the steps on https://github.com/QMCSoftware/QMCSoftware/blob/master/CONTRIBUTING.md 

This hopefully will resolve your problem.

**Comment by mblaszkiewicz** [comment]
Oh yes, no worries, got it! This definitely works, I simply go for another version of QMCPy, like 1.4.2.

**Comment by alegresor** [comment]
This is patched in the latest release, run `pip install -U qmcpy` to fix
