### ISSUE TITLE
Verify Licence for QMCPy

### ISSUE THREAD

**Issue by alegresor** [QMCSoftware/QMCSoftware#44]

**Comment by mikemccourt** [comment]
When I asked the CTO, his response was
```the agreement says it should be apache 2.0```
Is there a reason it is not?

**Comment by fjhickernell** [comment]
Let me look into this.

Best regards,
Fred


Fred J. Hickernell
Vice Provost for Research, research.iit.edu <https://research.iit.edu/>
Professor, Department of Applied Mathematics
Center for Interdisciplinary Scientific Computation (CISC) cos.iit.edu/cisc/ <https://cos.iit.edu/cisc/>
Illinois Institute of Technology
IIT Tower, Room 7C9-2, 10 W 35th St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, +1 312 567 3470 <tel:+1%20312%20567%203470>

**Comment by fjhickernell** [comment]
Illinois Tech general counsel has agreed to Apache 2.0 license.  Let's stick it in.
